[package]
name = "chess"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3"
tracing = "0.1"
tracing-subscriber = {  version = "0.3" , features = ["env-filter"]}

[dependencies.xxhash-rust]
version = "0.8.5"
features = ["xxh3", "const_xxh3"]